blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'   # 定义一个命名空间，用来区分不同应用之间的链接地址
urlpatterns = [
    path('', views.index, name='index'),#url的名字，方法，命名空间
    path('category/<int:categoty_id>/', views.category_list, name='category_list'),
    path('detail/<int:post_id>/',views.post_detail,name='post_detail'),
    path('search/',views.search,name='search')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
#静态文件配置
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),#第一个参数可以改成任意值 在网页中输入相应的值即可
    path('',include('blog.urls'))
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

#媒体文件配置
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'   # 定义一个命名空间，用来区分不同应用之间的链接地址
urlpatterns = [
    path(r'login.html', views.login_view, name='login'),#url的名字，方法，空间命名
    path(r'register.html', views.register, name='register'),
    path(r'active/<active_code>',views.active_user,name='active_user'),
    path(r'forget_pwd.html',views.forget_pwd,name='forget_pwd'),
    path(r'forget_pwd_url/<active_code>',views.forget_pwd_url,name='reset_pwd'),
    path(r'user_profile.html',views.user_profile,name='user_profile'),
    path(r'logout/',views.logout_view,name='logout1'),
    path(r'editor_users/',views.editor_users,name='editor_users'),
]
#r'^login/'

blog/models.py
from django.contrib.auth.models import User
from django.db import models

#博客侧边栏
from django.utils.functional import cached_property  # 缓存装饰器
from django.template.loader import render_to_string  # 渲染模板

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=32, verbose_name="分类名称")
    desc = models.TextField(max_length=200, blank=True, default='', verbose_name="分类描述")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "博客分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class Tag(models.Model):
    """ 文章标签 """
    name = models.CharField(max_length=10, verbose_name="文章标签")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "文章标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class Post(models.Model):
    """ 文章 """
    title = models.CharField(max_length=61, verbose_name="文章标题")
    desc = models.TextField(max_length=200, blank=True, default='', verbose_name="文章描述")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")#文章和类别关联起来
    content = models.TextField(verbose_name="文章详情")
    tags = models.ForeignKey(Tag, blank=True, null=True, on_delete=models.CASCADE, verbose_name="文章标签")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="作者")
    is_hot = models.BooleanField(default=False, verbose_name="是否热门")   # 手动热门推荐

    pv = models.IntegerField(default=0,verbose_name="浏览量")  # 浏览量
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class SideBar(models.Model):
    STATUS=(
        (1, '隐藏'),
        (2, '展示')
    )
    DISPLAY_TYPE=(
        (1, '搜索'),  #search
        (2, '最新文章'),  #new_post
        (3, '最热文章'),  #hot_post
        (4, '最近评论'),  #comment
        (5, '文章归档'),  #archives
        (6, 'HTML')
    )
    title = models.CharField(max_length=50, verbose_name="标题")
    display_type = models.PositiveIntegerField(default=1, choices=DISPLAY_TYPE, verbose_name="展示类型")
    content = models.CharField(max_length=500, blank=True, default='', verbose_name="内容",
                               help_text="如果设置的不是HTML类型，可为空")
    sort = models.PositiveIntegerField(default=1, verbose_name="排序", help_text='序号越大越靠前')
    status = models.PositiveIntegerField(default=2, choices=STATUS, verbose_name="状态")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name='侧边栏'
        verbose_name_plural=verbose_name
        ordering=['-sort']
    def __str__(self):
        return self.title

    @classmethod  # 类方法装饰器，这个就变成了这个类的一个方法可以调用
    def get_sidebar(cls):
        return cls.objects.filter(status=2)  # 查询到所有允许展示的模块

    @property  # 成为一个类属性，调用的时候不需要后边的（）,是只读的，用户没办法修改  get_content就是一个类
    def get_content(self):
        if self.display_type == 1:
            context = {

            }
            return render_to_string('blog/sidebar/search.html', context=context)
        elif self.display_type == 2:
            context = {

            }
            return render_to_string('blog/sidebar/new_post.html', context=context)
        elif self.display_type == 3:
            context = {

            }
            return render_to_string('blog/sidebar/hot_post.html', context=context)
        elif self.display_type == 4:
            context = {

            }
            return render_to_string('blog/sidebar/comment.html', context=context)
        elif self.display_type == 5:
            context = {

            }
            return render_to_string('blog/sidebar/archives.html', context=context)
        elif self.display_type == 6:
            return self.content # 在侧边栏直接使用这里的html，模板中必须使用safe过滤器去渲染HTML

blog/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

# Create your views here.
from blog.models import Category,Post,Tag
#django自带的分页方法
from django.core.paginator import Paginator

def index(request):
    #首页
    #category_list=Category.objects.all()
    post_list=Post.objects.all()
    paginator = Paginator(post_list, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'post_list': post_list, 'page_obj': page_obj}
    #context={'category_list':category_list,'post_List':post_list}
    return render(request,'blog/index.html',context)

#分类页 进行分页
def category_list(request,categoty_id):
    #分类列表 测试分类1 测试分类2
    category=get_object_or_404(Category,id=categoty_id)
    print(category)
    #获取当前分类下的所有文章 测试分类1的所有文章 测试分类2的所有文章
    posts=category.post_set.all()
    print(posts)
    paginator = Paginator(posts, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')  # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context={'category':category, 'page_obj': page_obj}#前面的参数是空间名 在前端html中要引用的话就要用前面那个参数
    return render(request,'blog/list.html',context)

#文章详情
def post_detail(request,post_id):
    #文章详页
    post=get_object_or_404(Post,id=post_id)
    print(post)
    prev_post=Post.objects.filter(id_lt=post_id).last()
    next_post = Post.objects.filter(id_gt=post_id).first()
    date_prev_post=Post.objects.filter(add_date_lt=post.add_date).last()
    date_next_post=Post.objects.filter(add_date_gt=post.add_date).first()
    context={'post':post,'prev_post':prev_post,'next_post':next_post}
    #print(context)
    return render(request,'blog/detail.html',context)

def search(request):
    #搜索视图
    keyword=request.GET.get('keyword')
    #没有搜索默认显示所有文章
    if not keyword:
        post_list=Post.objects.all()#内部自带查询方法 查询所有的文章
    else:
        post_list=Post.objects.filter(Q(title__icontains=keyword) | Q(desc__icontains=keyword) |Q(content__icontains=keyword))

    paginator=Paginator(post_list,2)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)


    context={
        'page_obj':page_obj
    }
    return render(request,'blog/index.html',context)

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static category %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %}
    <title>我的博客首页</title>
    {% endblock %}

{#    <link rel="stylesheet" href="{% static 'users/bulma.css' %}">#}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>

<body>
    <div class="pt-6">
    <nav class="navbar is-primary container" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https  ://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
      {% block navbar-start %}
        <div class="navbar-start">
          <a class="navbar-item">
            首页
          </a>
            {% get_category_list as category_list%}
            {% for category in category_list %}
                <a class="navbar-item" href="{% url 'blog:category_list' category.id %}">
                {{category.name}}
                </a>
            {% endfor %}

{#        {% endblock %}#}

          <a class="navbar-item">
            Documentation
          </a>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item">
                About
              </a>
              <a class="navbar-item">
                Jobs
              </a>
              <a class="navbar-item">
                Contact
              </a>
              <hr class="navbar-divider">
              <a class="navbar-item">
                Report an issue
              </a>
            </div>
          </div>
        </div>
        {% endblock %}
      {% block navbar-end %}
        <div class="navbar-end">
          <div class="navbar-item">
              {% if user.is_authenticated %}
{#                  <div class="buttons">#}
{#                    <a href="{% url 'users:user_profile' %}" class="button is-outlined">{{ request.user.username }}</a>#}
{#                    <a href="{% url 'users:logout1' %}" class="button is-primary">退出</a>#}
{#                  </div>#}

                  <div class="buttons">
                    <a class="button is-primary" href="{% url 'users:user_profile' %}" target="_blank">
                        <strong>{{ request.user.username }}</strong></a>
                    <a href="{% url 'users:logout1' %}" class="button is-primary">退出</a>
                  </div>



              {% else %}
                  <div class="buttons">
                    <a class="button is-primary" href="{% url 'users:register' %}" target="_blank">
                        <strong>注册</strong></a>
                  </div>
                  <a class="button is-light" href="{% url 'users:login' %}" target="_blank">
                登录
              </a>
              {% endif %}
          </div>
        </div>
      {% endblock %}
      </div>
    </nav>
</div>

<section class="section">
<div class="container">
    <div class="columns">
        <div class="column is-8">
            {% block left %}
                {% if page_obj %}
                {% for post in page_obj %}
{#                {% for post in post_List %}#}
                    <div class="box mt">
                        <h1 class="is-size-5 has-text-weight-bold" >
                            <a href="{% url 'blog:post_detail' post.id %}">
                                {{ post.title }}
                            </a>
                        </h1>
                        <div class="mr-3 is-size-7 has-text-grey-bold pt-1 pb-1">
                            <span>作者：{{ post.owner }}</span>
                            <span>发布日期：{{ post.add_date }}</span>
                        </div>
                        <p class="mt-3">{{ post.desc |truncatechars:50}}</p>
                    </div>
                {% endfor %}
                    {% else %}
                    <div class="box">
                    <p class="has-text-danger">文章不存在</p>
                    </div>
                {% endif %}
                {% if page_obj %}
                    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
                    {% if page_obj.has_previous %}
                        <a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    {% endif %}
                    {% if page_obj.has_next %}
                    <a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
                    {% endif %}
                    <ul class="pagination-list">
                    {% if page_obj.has_previous %}
                        <li><a class="pagination-link" aria-label="Goto page 45" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                    {% endif %}
                        <li><a class="pagination-link is-current" aria-label="Page {{ page_obj.number }}" aria-current="page" href='?page={{ page_obj.number }}'>{{ page_obj.number }}</a></li>
                    {% if page_obj.has_next %}
                        <li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}" aria-label="Goto page {{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                    {% endif %}
                    </ul>
                    </nav>
                {% endif %}
            {% endblock %}
        </div>
        {% block right %}
        <div class="column is-4">
                    {#    侧边栏#}
            {% get_sidebar_list as sidebar_list %}
            {% for sidebar in sidebar_list %}
                <div class="box">
                    <h1 class="is-size-5 title">{{ siderbar.title }}</h1>
                    <p>{{ sidebar.get_content | safe}}</p>
        </div>
{% endfor %}
                    </div>
        {% endblock %}
        </div>
</div>
</section>

    <div class="box">
    <div class="level-left">
        {% if prev_post %}
{#            上一篇是按钮 点击之后转到post_detail这个网页，该方法在views.py中调用的是post_detail方法，传入上一篇文章的id#}
            <span>上一篇：</span><a href="{% url 'blog:post_detail' prev_post.id %}">{{ prev_post.title }}</a>
        {% else %}
            <span class="has-text-danger-dark is-size-7">无上一篇</span>
        {% endif %}
    </div>

    <div class="level-right">
        {% if next_post %}
            <span>下一篇：</span><a href="{% url 'blog:post_detail' next_post.id %}">{{ next_post.title }}</a>
        {% else %}
            <span class="has-text-danger-dark is-size-7">无下一篇</span>
        {% endif %}
    </div>


    </div>


{% block footer %}
<footer class="footer container">
  <div class=" has-text-centered">
    这是博客的底部
  </div>
</footer>
{% endblock %}
{# {% for category in category_list %}#}
{#                {{ category.name }}<br/>#}
{#                {{ category.desc }}<br/>#}
{#            {% endfor %}#}

</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block left %}

    <div class="box">
    <h1 class="is-size-5 has-text-weight-bold" >
                            <a href="{% url 'blog:post_detail' post.id %}">
                                {{ post.title }}
                            </a>
                        </h1>
    <div class="mr-3 is-size-7 has-text-grey-bold pt-1 pb-1">
                            <span>作者：{{ post.owner }}</span>
                            <span>发布日期：{{ post.add_date }}</span>
                        </div>
    <div class="content">
    {{ post.content |safe }}
    </div>
    </div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

blog/templates/blog/list.html
{% extends 'blog/base.html' %}

{% block left %}
{#    这是分类列表项 就是那个文章分类点击下来得到的内容#}
{#    分类列表#}
{#    获取当前分类名称 直接引用views.py中的category变量  html中的测试分类1，测试分类2等类别#}
    {{ category }}
    {% for post in posts %}
        {{ post.title }}
    {% endfor %}
{#    {{ post_list }}#}
{#    {{ category.post_set.all }}#}
{% endblock %}