blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'   # 定义一个命名空间，用来区分不同应用之间的链接地址
urlpatterns = [
    path('', views.index, name='index'),#url的名字，方法，命名空间
    path('category/<int:categoty_id>/', views.category_list, name='category_list'),
    path('detail/<int:post_id>/',views.post_detail,name='post_detail'),
    path('search/',views.search,name='search')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
#静态文件配置
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),#第一个参数可以改成任意值 在网页中输入相应的值即可
    path('',include('blog.urls'))
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

#媒体文件配置
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'   # 定义一个命名空间，用来区分不同应用之间的链接地址
urlpatterns = [
    path(r'login.html', views.login_view, name='login'),#url的名字，方法，空间命名
    path(r'register.html', views.register, name='register'),
    path(r'active/<active_code>',views.active_user,name='active_user'),
    path(r'forget_pwd.html',views.forget_pwd,name='forget_pwd'),
    path(r'forget_pwd_url/<active_code>',views.forget_pwd_url,name='reset_pwd'),
    path(r'user_profile.html',views.user_profile,name='user_profile'),
    path(r'logout/',views.logout_view,name='logout1'),
    path(r'editor_users/',views.editor_users,name='editor_users'),
]
#r'^login/'

users/models.py
from django.db import models
# 首先引入django内置的一个用户User模型，然后通过一对一关联关系为默认的User扩展用户数据
from django.contrib.auth.models import User
# Create your models here.

#扩展用户模型的方法有两种，一种是模仿官方的方法，直接继承`AbstractUser`类来扩展用户数据，另外一种是通过一对一关系关联User类，来扩展用户数据，我这里选择采用第二种一对一关联的方式来扩展，这样的好处是不需要再setiings.py中另外配置，也有利于我们理解和学习django的关联关系用法。
#我们为默认的User扩展数据便是使用一对一关系即OneToOneField，字段来相互关联扩展，一个用户只能对应唯一的一组数据，因此上这里就必须使用一对一关系关联。

class UserProfile(models.Model):
    USER_GENDER_TYPE = (
        ('male', '男'),
        ('female', '女'),
    )
    owner = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='用户')
    nike_name = models.CharField('昵称', max_length=50, blank=True, default='')#提交表单时，允许这一项为空
    birthday = models.DateField('生日', null=True, blank=True)
    gender = models.CharField('性别', max_length=6, choices=USER_GENDER_TYPE, default='male')
    address = models.CharField('地址', max_length=100, blank=True, default='')
    image = models.ImageField(upload_to='images/%Y/%m', default='images/default.png', max_length=100,
                              verbose_name='用户头像')

    desc=models.TextField('个人简历',max_length=200,blank=True,default='') #可以为空 一开始不设置
    gexing = models.CharField('个性签名', max_length=100, blank=True, default='')

    class Meta:
        verbose_name = '用户数据'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.owner.username

class EmailVerifyRecord(models.Model):#邮箱验证码校验记录
    SEND_TYPE_CHOICES = (
        ('register', '注册'),
        ('forget', '找回密码'),
    )
    code=models.CharField('验证码',max_length=30)
    email=models.CharField('邮箱',max_length=50)
    send_type = models.CharField(choices=SEND_TYPE_CHOICES, max_length=10, default='register')
    send_time = models.DateTimeField('时间', auto_now_add=True)

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.code



users/forms.py
#之前是通过html定义表单并获取表单数据 现在通过forms.py来构建表单
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile



class LoginForm(forms.Form):
    username=forms.CharField(label='用户名',max_length=30,widget=forms.TextInput(attrs={
        'class':'input','placeholder':'用户名/邮箱'
    })) #网页中显示的输入框
    #使用widget参数来设置样式
    #最后一个参数让输入的密码不显示
    password = forms.CharField(label='密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class':'input','placeholder':'密码'
    }))
    def clean_password(self):
        username=self.cleaned_data.get('username')
        password=self.cleaned_data.get('password')
        if username==password:
            raise forms.ValidationError('密码用户名相同')
        return password

class RegisterForm(forms.ModelForm):
#class RegisterForm(LoginForm,forms.ModelForm):#通过继承上面的登录表单和ModelForm(主要是里面的save方法，在views.py中用到了)
    # username=forms.CharField(label='用户名',max_length=30,widget=forms.TextInput(attrs={
    #     'class': 'input', 'placeholder': '用户名/邮箱'
    # }))#前一个用户名在网页中是那个实体字label 后面一个用户名/邮箱在页面中是框框中的浅色字体
    email=forms.EmailField(label='邮箱',max_length=30,widget=forms.EmailInput(attrs={
            'class': 'input', 'placeholder': '邮箱'
        }))
    password=forms.CharField(label='密码',min_length=6,widget=forms.PasswordInput(attrs={
        'class': 'input',
        'placeholder': '密码'
    }))
    password1=forms.CharField(label='再次密码',min_length=6,widget=forms.PasswordInput(attrs={
        'class':'input',
        'placeholder':'再次密码'
    }))
    class Meta:
        model=User
        fields = ('email', 'password')
        #fields=('username','password')#注册页面中需要的属性就选出来放在这里
    def clean_email(self):
        email=self.cleaned_data.get('email')
        exists=User.objects.filter(email=email).exists()
        if exists:
            raise forms.ValidationError('邮箱已存在')
        return email
    def clean_username(self):
        username=self.cleaned_data.get('username')
        exists=User.objects.filter(username=username).exists()
        if exists:
            raise forms.ValidationError('用户名已存在')
        return username
    #验证两次密码是否一样
    def clean_password1(self):
        data=self.cleaned_data
        password=data['password']
        password1=data['password1']
        if password!=password1:
            raise forms.ValidationError('密码不一致')
        return password

#找回密码表单
class ForgetPwdForm(forms.Form):
    email=forms.EmailField(label='请输入邮箱地址',min_length=4, widget=forms.EmailInput(attrs={
        'class': 'input', 'placeholder': '用户名/邮箱'
    }))

#修改密码表单
class ModifyPwdForm(forms.Form):
    password=forms.CharField(label='输入新密码',min_length=6,widget=forms.PasswordInput(attrs={
        'class':'input',
        'placeholder':'输入新密码'
    }))

#修改用户信息的表单
class UserForm(forms.ModelForm):
    """ User模型的表单，只允许修改email一个数据，用户名不允许修改 """
    #邮箱信息是可以修改的
    class Meta:
        model = User
        fields = ('email',)
class UserProfileForm(forms.ModelForm):
    """ UserProfile的表单 """
    class Meta:
        """Meta definition for UserInfoform."""
        model = UserProfile
        fields = ('nike_name','desc', 'gexing', 'birthday',  'gender', 'address', 'image')

users/views.py
# users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.shortcuts import render,HttpResponse,redirect

from users.forms import LoginForm, RegisterForm, ForgetPwdForm, ModifyPwdForm,UserForm,UserProfileForm

#邮箱注册导入库  ModelBackend是Django使用的默认身份验证后端
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q

from users.models import EmailVerifyRecord
from utils.email_send import send_register_email

# 引入用户模型字段
from .models import UserProfile
from django.contrib.auth.decorators import login_required

# 本视图登录后才能访问，所以检测登录的装饰器一定要加
@login_required(login_url='users:login')   # 设置登录后才能访问，如果没有登陆，就跳转到login界面
def user_profile(request):
    user = User.objects.get(username=request.user)#获取该用户
    return render(request, 'users/user_profile.html', {'user': user})



def login_view(request):
    # if request.method=='POST':
    #     username=request.POST['username'] #后面的username参数是来自前端html中定义的表单
    #     password=request.POST['password']# request.POST[]或request.POST.get()获取数据
    #     #print(username,password)
    #     # 与数据库中的用户名和密码比对，django默认保存密码是以哈希形式存储，并不是明文密码，这里的password验证默认调用的是User类的check_password方法，以哈希值比较。
    #     user = authenticate(request, username=username, password=password)
    #     if user is not None:
    #         # 验证如果用户不为空
    #         #login方法登录
    #         login(request,user)#内置登录函数
    #         return HttpResponse('登录成功') #在网页中返回登陆成功
    #     else:
    #         # 返回登录失败信息
    #         return HttpResponse('登陆失败')
    if request.method!='POST':
        form = LoginForm()#空表单
    else:
        form=LoginForm(request.POST)#获取之后存到了一个cleaned_data字典中
        if form.is_valid():
            username=form.cleaned_data['username']
            password= form.cleaned_data['password']
            user=authenticate(request,username=username,password=password)
            if user is not None:
                login(request,user)
                #跳转
                #return redirect('/admin')
                return redirect('users:user_profile')
                #return HttpResponse('success login')
            else:
                # 验证不通过提示！
                return HttpResponse("账号或者密码错误！")
    context={'form':form}

    return render(request, 'users/login.html',context)

def register(request):
    #注册视图
    if request.method!='POST':
        form=RegisterForm()
    else:
        form=RegisterForm(request.POST)
        if form.is_valid():
            new_user=form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.username=form.cleaned_data.get('email')#注注册的时候把email赋值给新用户的username，username和email一样了

            new_user.save()
            send_register_email(form.cleaned_data.get('email'),'register')
            return redirect('users:login')#注册完成转到登录页面
    context={'form':form}
    return render(request, 'users/register.html',context)

class MyBackend(ModelBackend): #email register login
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user=User.objects.get(Q(username=username)|Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None

def active_user(request,active_code):
    #查询验证码 修改用户状态
    all_records=EmailVerifyRecord.objects.filter(code=active_code)
    if all_records:
        for record in all_records:
            email=record.email #得到邮箱
            print(email)
            user=User.objects.get(email=email)  #获取用户
            print(user)
            user.is_staff=True
            user.save()

    else:
        return HttpResponse('链接有错')
    return redirect('users:login')

def forget_pwd(request):
    '找回密码'
    if request.method=='GET':
        form=ForgetPwdForm()#空表单
    elif request.method=='POST':
        form=ForgetPwdForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data.get('email')
            exists=User.objects.filter(email=email).exists()
            if exists:
                #发送邮件
                send_register_email(email,'forget')
                return HttpResponse('邮件已发送请查收')
            else:
                return HttpResponse('邮箱未注册 请注册')
    return render(request,'users/forget_pwd.html',{'form':form})

def forget_pwd_url(request,active_code):
    #修改密码
    if request.method!='POST':
        form=ModifyPwdForm()
    else:
        form=ModifyPwdForm(request.POST)
        if form.is_valid():
            record=EmailVerifyRecord.objects.get(code=active_code)
            email=record.email
            user=User.objects.get(email=email)
            user.username=email
            user.password = make_password(form.cleaned_data.get('password'))
            user.save()
            return HttpResponse('修改成功')
        else:
            return HttpResponse('修改失败')

    return render(request, 'users/reset_pwd.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('users:login')

@login_required(login_url='users:login')   # 设置登录后才能访问，如果没有登陆，就跳转到login界面
def editor_users(request):
    #编辑用户信息
    user=User.objects.get(id=request.user.id)
    if request.method=='POST':
        try:
            #user和userprofile之间是一对一的关系，默认注册的时候是没有数据的，注册成功之后才会在个人中心显示信息
            #第一次登录应该是空表单，如果设置了信息，以后编辑的话就是修改，应该要默认显示原有数据
            userprofile=user.userprofile #模型名称的小写直接拿到用户数据
            form= UserForm(request.POST, instance=user)#instance=user默认显示原有的数据
            print(form)
            user_profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)  # 向表单填充默认数据
            print(user_profile_form)
            if form.is_valid() and user_profile_form.is_valid():
                form.save()
                user_profile_form.save()
                return redirect('users:user_profile')
        except UserProfile.DoesNotExist:  # 这里发生错误说明userprofile无数据
            form = UserForm(request.POST, instance=user)  # 填充默认数据 当前用户 如果userprofile不存在的话 代入user的值
            user_profile_form = UserProfileForm(request.POST, request.FILES)  # 空表单，直接获取空表单的数据保存
            if form.is_valid() and user_profile_form.is_valid():
                form.save()
                # commit=False 先不保存，先把数据放在内存中，然后再重新给指定的字段赋值添加进去，提交保存新的数据
                new_user_profile = user_profile_form.save(commit=False)
                new_user_profile.owner = request.user  #把提交的user（修改的用户名）赋值给models中的owner属性
                new_user_profile.save()
                return redirect('users:user_profile')
    else:
        try:
            userprofile = user.userprofile
            form = UserForm(instance=user)
            user_profile_form = UserProfileForm(instance=userprofile)
        except UserProfile.DoesNotExist:
            form = UserForm(instance=user)
            user_profile_form = UserProfileForm()  # 显示空表单
    return render(request, 'users/editor_users.html', locals())

users/templates/users/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <title>登陆页面</title>
    {% endblock head %}
    <link rel="stylesheet" href="{% static 'users/bulma.css' %}">
</head>

<body>
<div class="container">
    {% block content %}
    {% endblock content %}
</div>

</body>
</html>

users/templates/users/editor_users.html
{% extends 'users/user_profile.html' %}

{#继承了上面那个文件的样式模板，只用修改block包裹的那部分进行覆盖，其他部分就和模板中样式一样#}
{% block title %}
<li class="is-active"><a>账号信息</a></li>
{% endblock title %}
{% block content %}
    <div class="content">
    <fieldset disabled style="margin-bottom: 1em">
        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label">用户名</label>
          </div>
          <div class="field-body">
            <div class="field">
              <p class="control is-expanded has-icons-left">
                <input class="input" type="text" placeholder="Name" value="{{ user.username }}">
                <span class="icon is-small is-left">
                  <i class="fas fa-user"></i>
                </span>
              </p>
            </div>
          </div>
        </div>
    </fieldset>


    <form action="{% url 'users:editor_users' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label for="{{ form.email.id_for_label }}" class="label">{{ form.email.label }}</label>
          </div>
          <div class="field-body">
            <div class="field">
              <div class="control">
                  {{ form.email }}
              </div>
            </div>
          </div>
      </div>
        {% for field in user_profile_form %}
        <div class="field is-horizontal">
            <div class="field-label is-normal">
              <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
            </div>
            <div class="field-body">
              <div class="field">
                <div class="control">
                   {{ field }}
                </div>
              </div>
            </div>
        </div>
        {% endfor %}
        <input class=" button is-primary is-pulled-right" type="submit" value="保存修改">
        <div class=" is-clearfix"></div>

        </form>
    </div>
{% endblock content %}

users/templates/users/forget_pwd.html
{% extends 'users/base.html' %}

{% block head %}
    <title>填写邮箱地址</title>
{% endblock head %}


{% block content %}
    <div class="box">
        <h1 class="is-uppercase has-text-centered has-text-weight-bold">轻编程
            <br><span class="tag">找回密码</span>
        </h1>
        <hr class="dropdown-divider">
        <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" style="margin-top: 1em" class="button is-link is-fullwidth" value="发送邮件">
        <a class="is-pulled-right is-size-7" href="{% url 'users:forget_pwd' %}">忘记密码？</a>
        </form>
    </div>
{% endblock content %}


users/templates/users/login.html
{% extends 'users/base.html' %}
{% block head %}
    <title>登陆页面</title>
{% endblock head %}

{% block content %}
    <div class="box">
        <h1 class="is-uppercase has-text-centered has-text-weight-bold">轻编程
            <br><span class="tag">登录</span>
        </h1>
        <hr class="dropdown-divider">
        <form action="" method="post">
        {% csrf_token %}
{#        <label for="id_username">用户名：</label>#}
{#        <input type="text" name="username" id="id_username">#}
{#        <label for="id_password">密码：</label>#}
{#        <input type="password" name="password" id="id_password">#}
        {{ form.as_p }}
        <input type="submit" style="margin-top: 1em" class="button is-link is-fullwidth" value="登录">
        <a class="is-pulled-right is-size-7" href="{% url 'users:forget_pwd' %}">忘记密码？</a>
        </form>
    </div>


{% endblock content %}

{#<!DOCTYPE html>#}
{#{% load static %}#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewpoint" content="width=device-width, initial-scale=1.0">#}
{#    <title>登陆页面</title>#}
{#    <link rel="stylesheet" href="{% static 'users/bulma.css' %}">#}
{#</head>#}
{#<body>#}
{#<div class="container">#}
{##}
{#</div>#}
{#</body>#}
{#</html>#}

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/users/user_profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>个人中心</title>
    <link rel="stylesheet" href=" {% static 'users/bulma.css' %} ">
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    <script src=" {% static 'users/js/all.min.js' %}"></script>
</head>
<body>
    <!-- 头部导航 -->
    <nav class="navbar">
        <div class="container">
            <div class="navbar-brand">
                <a href="\" class="navbar-item">
                    <img src="{% static 'users/images/logo.png' %}" width="112" height="28" alt="logo">
                </a>
                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class=" dropdown is-hoverable">
                            <div class="dropdown-trigger">
                                <button class=" button is-white">
                                    <figure class="image is-24x24">

                                        {% if user.userprofile.image %}
                                            <img class=" is-rounded" src="{{ MEDIA_URL }}{{ user.userprofile.image }}" alt="" srcset="">
                                        {% else %}
                                            <img class=" is-rounded" src="{% static 'users/images/avatar.jpg' %}" alt="" srcset="">
                                        {% endif %}
                                    </figure>&nbsp;&nbsp;

                                        {% if user.userprofile.nike_name %}
                                        <span class="has-text-grey-dark">{{ user.userprofile.nike_name }}</span>
                                        {% else %}
                                        <span class="has-text-grey-dark">{{ user.username }}</span>
                                        {% endif %}
                                        <span class="icon is-small">
                                            <i class="fas fa-angle-down" aria-hidden="true"></i>
                                        </span>
                                </button>
                            </div>

                            <div class="dropdown-menu" id="dropdown-menu2" role="menu" >
                                <div class="dropdown-content is-shadowless">
                                    <div class="dropdown-item">
                                        <a class=" has-text-grey-dark" href="">
                                            <span class="icon is-small">
                                                <i class="fas fa-user-cog" aria-hidden="true"></i>
                                            </span>&nbsp;&nbsp;
                                           <a href="{% url 'users:editor_users' %}">账号设置</a>
                                           <!-- 点击账号设置就跳转到editor_users页面 -->
                                        </a>
                                    </div>
                                    <hr class="dropdown-divider">
                                    <div class="dropdown-item">
                                        <a class=" has-text-grey-dark" href="{% url 'users:logout1' %}">
                                            <span class="icon is-small">
                                                <i class="fas fa-power-off" aria-hidden="true"></i>
                                            </span>&nbsp;&nbsp;
                                            退出登录
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </nav>

    <section class="section">
        <div class="container">

            <div class="columns">
                <div class="column is-2">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">个人中心</p>
                            <a href="" class="card-header-icon" aria-label="more options">
                                <span class="icon">
                                    <i class="fas fa-angle-down" aria-hidden="true"></i>
                                </span>
                            </a>
                        </header>
                        <div class="card-content menu">
                            <ul class="content menu-list">
                               {#这里user_profile是那个urls中name=后面的值#}
                                <li><a href="{% url 'users:user_profile' %}">个人信息</a></li>
                                <!-- <li><a href="">修改密码</a></li> -->

                            </ul>
                        </div>

                    </div>
                    <div class="card">
                            <header class="card-header">
                                <p class="card-header-title">内容管理</p>
                                <a href="#" class="card-header-icon" aria-label="more options">
                                    <span class="icon">
                                        <i class="fas fa-angle-down" aria-hidden="true"></i>
                                    </span>
                                </a>
                            </header>
                            <div class="card-content menu">
                                <ul class="content menu-list">
                                    <li><a href="">添加文章</a></li>
                                    <li><a href="">已发布</a></li>
                                    <li><a href="">草稿箱</a></li>
                                    <li><a href="">评论管理</a></li>
                                    <li><a href="">数据分析</a></li>
                                </ul>
                            </div>

                    </div>
                </div>
                <div class="column is-10">
                    <div class="box is-radiusless is-shadowless">

                        <div class="tabs">
                            <ul>

                              {% block title %}
                              <li class="is-active"><a>账号信息</a></li>
                              {% endblock title %}

                            </ul>
                        </div>



                    {% block content %}
                    <div class="columns is-mobile" style="border-bottom: #ededed solid 1px; padding-bottom: 1rem">
                        <div class="column is-narrow">
                            <figure class="image is-96x96">

                                {% if user.userprofile.image %}
                                    <img class="is-rounded" src="{{ MEDIA_URL }}{{ user.userprofile.image }}">
                                    {% else %}
                                    <img class="is-rounded" src=" {% static 'users/images/avatar.jpg' %}">
                                {% endif %}


                            </figure>
                        </div>
                        <div class="column is-narrow">
                            <div style="padding-top: 1.5rem;">

                                {% if user.userprofile.nike_name %}
                                    <h1 class="title is-size-4">{{ user.userprofile.nike_name }}</h1>
                                    {% else %}
                                    <h1 class="title is-size-4">{{ user.username }}</h1>
                                {% endif %}


                                {% if user.userprofile.gexing %}
                                    <p class="subtitle is-size-6">{{ user.userprofile.gexing }}</p>
                                    {% else %}
                                    <p class="subtitle is-size-6">暂未设置个性签名</p>
                                {% endif %}


                            </div>
                        </div>
                        <div class="column is-narrow-mobile">
{#                            <a class=" button is-light is-pulled-right" href="{% url 'users:editor_users' %}" style="margin-top: 1.8rem">修改信息</a>#}
                        </div>
                    </div>

                    <div class="columns" style="padding:1rem 0; ">
                        <div class="column is-2">
                            <p>个人信息</p>
                        </div>
                        <div class="column">
                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">昵称</span>
                                </div>
                                    <div class="column is-narrow">
                                        {% if user.userprofile.nike_name %}
                                        <span class=" has-text-black-ter">{{ user.userprofile.nike_name }}</span>
                                        {% else %}
                                        <span class=" has-text-black-ter">暂未设置用户昵称</span>
                                        {% endif %}

                                    </div>
                                <!-- <div class="column has-text-right">
                                    <a href="">更改类型</a>
                                </div> -->

                            </div>
                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">性别</span>
                                </div>
                                <div class="column is-narrow">
                                    {% if user.userprofile %}
                                    <span class=" has-text-black-ter">{{ user.userprofile.get_gender_display }}</span>
                                    {% else %}
                                    <span class=" has-text-black-ter">暂未设置</span>
                                    {% endif %}
                                </div>

                            </div>
                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">邮箱</span>
                                </div>
                                <div class="column is-narrow">
                                    <span class=" has-text-black-ter">{{ user.email }}</span>
                                </div>

                            </div>

                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">地址</span>
                                </div>
                                <div class="column is-narrow">
                                    {% if user.userprofile %}
                                    <span class=" has-text-black-ter">{{ user.userprofile.address }}</span>
                                    {% else %}
                                    <span class=" has-text-black-ter">暂未添加地址</span>
                                    {% endif %}

                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="columns" style="padding:1rem 0; ">
                        <div class="column is-2">
                            <p>个人简介</p>
                        </div>
                        <div class="column">
                            <div class="content">
                                {% if user.userprofile.desc %}
                                {{ user.userprofile.desc }}
                                {% else %}
                                暂未设置
                                {% endif %}

                            </div>
                        </div>
                    </div>
                    {% endblock  %}

                    </div>
                </div>
            </div>

        </div>
    </section>



</body>
</html>